FROM slicerros_csc379 as system

ENV DEBIAN_FRONTEND=noninteractive

# for slicer ros2
USER root
RUN apt-get update && apt-get install -y python3-colcon-common-extensions ros-humble-ament-cmake ros-humble-joint-state-publisher ros-humble-xacro

# Extra ROS2 missing for franka_gripper
RUN apt-get install -y ros-humble-control-msgs ament-cmake-clang-format

# USER csc379
# WORKDIR /home/csc379
# RUN mkdir -p /home/csc379/ros2_ws/src
# RUN cd /home/csc379/ros2_ws/src && git clone https://github.com/rosmed/slicer_ros2_module
# WORKDIR /home/csc379/ros2_ws
# RUN source /opt/ros/humble/setup.bash && colcon build --cmake-args -DSlicer_DIR:PATH=/home/csc379/slicer/Slicer-SuperBuild-Debug/Slicer-build -DCMAKE_BUILD_TYPE=Release


# franka_bringup && franka_description, might want from scratchpad instead
# USER csc379
# WORKDIR /home/csc379/ros2_ws/src
# RUN git clone https://mcsgitlab.utm.utoronto.ca/iseoluwa/franka_bringup.git
# RUN git clone https://mcsgitlab.utm.utoronto.ca/iseoluwa/franka_description.git
# WORKDIR /home/csc379/ros2_ws
# RUN source /opt/ros/humble/setup.bash && colcon build

# libfranka install
## From https://github.com/frankaemika/libfranka/blob/main/README.md
USER root
WORKDIR /home/csc379/

RUN apt-get update
RUN apt-get install -y build-essential cmake git libpoco-dev libeigen3-dev dpkg

# libfranka build
RUN apt remove "*libfranka*"
USER csc379
WORKDIR /home/csc379/
RUN git clone --recursive https://github.com/frankaemika/libfranka.git
WORKDIR /home/csc379/libfranka
RUN git checkout 0.9.2 \
    && git submodule update --init --recursive \
    && mkdir build \ 
    && cd build \ 
    && cmake .. -DCMAKE_BUILD_TYPE=Release \
    && make -j4 \
    && cpack -G DEB

USER root
WORKDIR /home/csc379/libfranka/build
RUN dpkg -i libfranka*.deb

# tmux
RUN apt install tmux

# Peter Corkes Robotics toolbox
RUN apt-get update && apt-get install -y python3-pip

# aliases
SHELL ["/bin/bash", "-c"]
# RUN echo 'alias s_ros="source /opt/ros/humble/setup.bash && source /home/csc379/ros2_ws/install/setup.bash"' >> ~/.bashrc
RUN echo 'alias slicer="/home/csc379/slicer/Slicer-SuperBuild-Debug/Slicer-build/Slicer"' >> /root/.bashrc

RUN pip3 install roboticstoolbox-python pygame numpy==1.26.4 
# Have to add numpy version as sometimes robotics toolbox installs an incorrect version

# Login, this doesnt make sense as we run as root in docker-compose.yml
USER csc379
WORKDIR /home/csc379

ENV DISPLAY=:0
ENTRYPOINT ["/bin/bash"]
