FROM slicerros_csc379 as system

ENV DEBIAN_FRONTEND=noninteractive

# franka_bringup && franka_description, might want from scratchpad instead
USER csc379
WORKDIR /home/csc379/ros2_ws/src
RUN git clone https://mcsgitlab.utm.utoronto.ca/iseoluwa/franka_bringup.git
RUN git clone https://mcsgitlab.utm.utoronto.ca/iseoluwa/franka_description.git
WORKDIR /home/csc379/ros2_ws
RUN source /opt/ros/humble/setup.bash && colcon build

# libfranka install
## From https://github.com/frankaemika/libfranka/blob/main/README.md
USER root
WORKDIR /home/csc379/

RUN apt-get update
RUN apt-get install -y build-essential cmake git libpoco-dev libeigen3-dev dpkg

## pinnochio? for 0.14.0
RUN apt-get install -y liburdfdom-headers-dev libconsole-bridge-dev libtinyxml2-dev
RUN apt-get install -qqy lsb-release curl

RUN mkdir -p /etc/apt/keyrings
RUN curl http://robotpkg.openrobots.org/packages/debian/robotpkg.asc | tee /etc/apt/keyrings/robotpkg.asc
RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/robotpkg.asc] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg" \
| tee /etc/apt/sources.list.d/robotpkg.list
RUN apt-get update && apt-get install -qqy robotpkg-pinocchio

## libfranka build
RUN apt remove "*libfranka*"
USER csc379
WORKDIR /home/csc379/
RUN git clone --recursive https://github.com/frankaemika/libfranka.git
WORKDIR /home/csc379/libfranka
RUN git checkout 0.14.1
RUN git submodule update
RUN mkdir build
WORKDIR /home/csc379/libfranka/build
RUN export CMAKE_PREFIX_PATH=/opt/openrobots/lib/cmake \
    && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF [-DCMAKE_PREFIX_PATH=/opt/openrobots/lib/cmake] .. \
    && cmake --build . \
    && cpack -G DEB

USER root
WORKDIR /home/csc379/libfranka/build
RUN dpkg -i libfranka*.deb

# Peter Corkes Robotics toolbox
RUN apt-get update && apt-get install -y python3-pip

## pip as non root and also for setup the container entry
USER csc379
WORKDIR /home/csc379
RUN pip3 install roboticstoolbox-python 

ENV DISPLAY=:0
ENTRYPOINT ["/bin/bash"]
