FROM ros:humble-desktop

ENV DEBIAN_FRONTEND=noninteractive

# for ROS2 dependencies
RUN apt-get update && apt-get install -y python3-colcon-common-extensions ros-humble-ament-cmake ros-humble-joint-state-publisher ros-humble-xacro

# libfranka install
RUN apt-get update
RUN apt-get install -y build-essential cmake git libpoco-dev libeigen3-dev dpkg

# libfranka build
RUN apt remove -y "*libfranka*" || true
WORKDIR /home/
RUN git clone --recursive https://github.com/frankaemika/libfranka.git
WORKDIR /home/libfranka
RUN git checkout 0.9.2 \
    && git submodule update --init --recursive \
    && mkdir build \ 
    && cd build \ 
    && cmake .. -DCMAKE_BUILD_TYPE=Release \
    && make -j4 \
    && cpack -G DEB

WORKDIR /home/libfranka/build
RUN dpkg -i libfranka*.deb

# Development tools
RUN apt install -y tmux python3-pip

# Python libraries
RUN pip3 install roboticstoolbox-python pygame numpy==1.26.4

WORKDIR /home
ENV DISPLAY=:0
ENTRYPOINT ["/bin/bash"]